version: "3.4"

services:
  whoami:
    image: rbekker87/golang-whoami:latest
    ports:
      - 81:80
    networks:
      - web_net
    deploy:
      mode: replicated
      replicas: 2

networks:
  web_net: {}
